create animals table
naji-97/Vet-Clinic-dataBases pull request #1
Opened 2023-06-05 21:06 UTC by naji-97

- [ ] Create a table named animals
- [ ] Copy the SQL I used in the previous point into the schema.sql file in the generated repository.
- [ ] Copy the SQL I used in the previous point into the data.sql file in the generated repository.
- [ ] Take a screenshot of the results of my queries.
- [ ]  screenshot 
- [ ]  [query1.](./img/vet-clinic-1.png)
- [ ]  [query2](vet-clinic-2.png)

2023-06-05 21:23 UTC, 1GORDON reviewed
##
## Hi @naji-97 ✋

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and won't affect the number of your weekly reviews.

- [ ] Kindly customize your readme file properly. You may fix the broken issues link to make it more professional.
- [ ] You may include 1-3 descriptive potential features to be added. Add this to your Future Features section.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 09:31 UTC, DeliceLydia requested changes
## Hi @naji-97, 

Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Good README
- [ ] Followed git workflow

## Required Changes ♻️
_Check the comments under the review._



### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 09:31 UTC, DeliceLydia commented on schema.sql
>  );
- [ ] Please add a new column called `species` in the `animal` table

2023-06-06 09:31 UTC, DeliceLydia commented on data.sql
> +  ('Devimon', '2017-05-12', 5, true, 11);
- [ ] Please all data provided in the `animal` table

2023-06-06 09:31 UTC, DeliceLydia commented on queries.sql
> +
- [ ] Please create queries to answer questions provided

2023-06-06 09:33 UTC, mukhammadrizooff approved these changes
Hi @naji-97, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 09:56 UTC, merged